# Generated by Django 4.1 on 2022-08-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2000-10-23'),
            preserve_default=False,
        ),
    ]
